<a href="https://colab.research.google.com/github/byiringiroscar/NLP_FELLOWSHIP/blob/main/pytorch_documentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

#create 1d torch

In [2]:
x = torch.empty(1) 

#create 2d torch

In [3]:
x = torch.empty(2, 3)
x

tensor([[6.9688e-34, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

#create 3d torch 

In [4]:
x = torch.empty(3, 3, 3)
x

tensor([[[6.9349e-34, 0.0000e+00, 1.3452e-43],
         [0.0000e+00,        nan, 0.0000e+00],
         [2.8937e+12, 7.5338e+28, 7.2053e+22]],

        [[4.7428e+30, 6.9983e+28, 1.2412e+28],
         [1.0304e+21, 2.7495e+26, 5.6502e-02],
         [1.8728e+31, 7.3867e+20, 2.0027e-19]],

        [[7.8026e+34, 1.0894e+27, 1.4603e-19],
         [1.6795e+08, 4.7423e+30, 4.7393e+30],
         [9.5461e-01, 4.4377e+27, 1.7975e+19]]])

#create empty zeros and ones

In [5]:
x = torch.zeros(2, 2) # 2d dimension
x

tensor([[0., 0.],
        [0., 0.]])

In [6]:
x = torch.zeros(2, 2, dtype=torch.int) # change dataype
x

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

#create your tensor 

In [7]:
x = torch.tensor([2.5, 0.1, 2.3]) # create 1d tensor
x

tensor([2.5000, 0.1000, 2.3000])

# let's see randon with torch , add, sub, div , mul

In [8]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x

tensor([[0.8237, 0.5609],
        [0.3445, 0.1025]])

In [9]:
z = x + y
z = torch.add(x, y)

inplace addition


In [10]:
y.add_(x) # inplace will modifie y variable add with x
y

tensor([[1.1193, 0.7634],
        [0.5073, 0.2899]])

In [11]:
z = torch.sub(x, y)
z = x-y
z = torch.mul(x, y)
z = x*y
z = torch.div(x, y)
z=x/y

#create random with 2d dimension then do slicing

In [12]:
# remember rows go vertical | and column go horizontal __  and(rows, column)
x = torch.rand(5, 3)
print(x)
print(x[:, 1]) # this will print all rows in column 1
print(x[1,:]) # this will print rows 1 and all column  

tensor([[0.7414, 0.6706, 0.6119],
        [0.7440, 0.0115, 0.7876],
        [0.9239, 0.7206, 0.5238],
        [0.7159, 0.3696, 0.2893],
        [0.9741, 0.2923, 0.4662]])
tensor([0.6706, 0.0115, 0.7206, 0.3696, 0.2923])
tensor([0.7440, 0.0115, 0.7876])


In [13]:
print(x[1,1])
print(x[1,1].item()) # print actual element 

tensor(0.0115)
0.01145780086517334


#reshape tensor

In [14]:
x = torch.rand(4,4)
y = x.view(16) #  4*4 = 16
print(y) # will be in 1d

tensor([0.0909, 0.6753, 0.3861, 0.1855, 0.7466, 0.1684, 0.3294, 0.8813, 0.6639,
        0.1440, 0.5890, 0.3444, 0.0834, 0.0477, 0.7110, 0.7131])


In [15]:
y = x.view(-1, 8) # this will take 2d with 8,8

#convert tensor to numpy

In [16]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [17]:
b = a.numpy()
print(type(b)) # convert a tensor to numpy array

<class 'numpy.ndarray'>


N:B when we tensor are running on cpu not on gpu will share same memory then effect from one it will effect others
because they are sharing same memory location

In [18]:

a
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [19]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [20]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [21]:
b = torch.from_numpy(a) # by default it will have datatype torch.float64

In [22]:
a += 1

In [23]:
a

array([2., 2., 2., 2., 2.])

In [24]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

#if we are running on cuda toolkit

In [25]:
# we can check it by this
if torch.cuda.is_available():
  device = torch.device("cuda") # when you are on window and you have cuda available
  #create tensor on gpu
  x = torch.ones(5, device=device) # this will create tensor then put on gpu
  # or we can do like this
  y = torch.ones(5)
  y = y.to(device=device) # and it will be much fast
  z = x +y
  #z.numpy() # this will return error because numpy handle cpu tensor we have to move it back to cpu
  z = z.to("cpu")
else:
  print("no")

no


In [26]:
x = torch.ones(5, requires_grad=True) # this will pytorch that we will be using gradient in optimization later
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

#autograd package
this will help us in our model optimization

In [27]:
x = torch.randn(3, requires_grad=True)
print(x)
y = x +2 # here our input is x and 2  
print(y)

tensor([0.1017, 2.2341, 0.1599], requires_grad=True)
tensor([2.1017, 4.2341, 2.1599], grad_fn=<AddBackward0>)


grad can be implicitly created only for scalar outputs solve this error by creating torch with same dimension then pass it in backward

In [33]:
z = y*y*2
#z = z.mean()
v = torch.tensor([0.1, 1.0, 0.001], dtype=torch.float32)
z

tensor([ 8.8343, 35.8558,  9.3307], grad_fn=<MulBackward0>)

calculate gradient

In [34]:
#z.backward() # calculate gradient # dz/dx
#print(x.grad)
z.backward(v)
print(x.grad)

tensor([ 3.6430, 22.5820,  2.8886])


# prevent pytorch to track our history so we have 3 option to solve it


1.   x.requires_grad_(False)
2.   x.detach()
3.   with torch.no_grad():






In [35]:
x = torch.randn(3, requires_grad=True)
x

tensor([-1.5471,  0.6565,  0.1875], requires_grad=True)

option 1

In [36]:
x.requires_grad_(False)
x

tensor([-1.5471,  0.6565,  0.1875])

option 2

In [37]:
y = x.detach()
y

tensor([-1.5471,  0.6565,  0.1875])

option 3

In [38]:
with torch.no_grad():
  y = x+2
  print(y)

tensor([0.4529, 2.6565, 2.1875])


In [51]:
weights = torch.ones(4, requires_grad=True)
print(weights)


for epoch in range(3):
  print("weights *****************", weights)
  model_output = (weights*3).sum()
  print("model_output *****************", model_output)
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_() # before we do the next iteration and optimization we must empty the gradient

  print("========================================end=====================")

tensor([1., 1., 1., 1.], requires_grad=True)
weights ***************** tensor([1., 1., 1., 1.], requires_grad=True)
model_output ***************** tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
========================================end=====================
weights ***************** tensor([1., 1., 1., 1.], requires_grad=True)
model_output ***************** tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
========================================end=====================
weights ***************** tensor([1., 1., 1., 1.], requires_grad=True)
model_output ***************** tensor(12., grad_fn=<SumBackward0>)
tensor([3., 3., 3., 3.])
========================================end=====================


#let's see example by using built in optimizer

In [53]:
weights = torch.ones(4, requires_grad=True)
optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad() # here we do it before we got to the next iteration

#backpropagation

In [57]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

# forward pass and compute the loss
y_hat = w *x
loss = (y_hat - y)**2
print(loss)

# backward pass
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


# gradient descent using Autograd






1.   prediction:Manually
2.   Gradients Computation: Manually
2.   loss Computation: Manually
2.   Parameter updates: Manually

#built our gradients with numpy and we are doing this implementation manually

In [76]:
# # f = w * x
# # f = 2 * x

# X = np.array([1,2,3,4], dtype=np.float32)
# Y = np.array([2,4,6,8], dtype=np.float32) # since our formular above comment 2 * x 
# w = 0.0
# # model prediction
# def forward(x):
#   return w*x


# # loss  = MSE(MEAN SQUARED ERROR) this happen in case of linear regression
# def loss(y, y_predicted):
#   return ((y_predicted -y)**2).mean()


# #gradient 
# #MSE = 1/N *(w*x -y)**2
# #dJ/dw = 1/n 2*x (w*x -y)

# def gradient(x, y, y_predicted):
#   return np.dot(2*x, y_predicted-y).mean()

# print(f'Prediction before training: f(5) = {forward(5):.3f}')

# #training
# learning_rate = 0.01
# n_iters = 20

# for epoch in range(n_iters):
#   #prediction = forwad pass
#   y_pred = forward(X)
#   #loss
#   l = loss(Y, y_pred)
#   #gradients

#   dw = gradient(X, Y, y_pred)
#   #update weights
#   w -= learning_rate * dw
#   if epoch % 2 == 0:
#     print(f'epoch {epoch+1}: w = {w:.3f}, loss={l:.8f}')
# print(f'Prediction after training: f(5) = {forward(5):.3f}')


#built this gradients with torch 

In [80]:
# f = w * x
# f = 2 * x

X = torch.tensor([1,2,3,4], dtype=torch.float32)
Y = torch.tensor([2,4,6,8], dtype=torch.float32) # since our formular above comment 2 * x 
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
# model prediction
def forward(x):
  return w*x


# loss  = MSE(MEAN SQUARED ERROR) this happen in case of linear regression
def loss(y, y_predicted):
  return ((y_predicted -y)**2).mean()



print(f'Prediction before training: f(5) = {forward(5):.3f}')

#training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
  #prediction = forwad pass
  y_pred = forward(X)
  #loss
  l = loss(Y, y_pred)

  #gradients = backward pass

  l.backward()
  #update weights
  with torch.no_grad():
    w -= learning_rate * w.grad
  # zero gradients this is for help us to put this w 0 after our epoch
  w.grad.zero_()
  if epoch % 10 == 0:
    print(f'epoch {epoch+1}: w = {w:.3f}, loss={l:.8f}')
print(f'Prediction after training: f(5) = {forward(5):.3f}')


Prediction before training: f(5) = 0.000
epoch 1: w = 0.300, loss=30.00000000
epoch 11: w = 1.665, loss=1.16278565
epoch 21: w = 1.934, loss=0.04506890
epoch 31: w = 1.987, loss=0.00174685
epoch 41: w = 1.997, loss=0.00006770
epoch 51: w = 1.999, loss=0.00000262
epoch 61: w = 2.000, loss=0.00000010
epoch 71: w = 2.000, loss=0.00000000
epoch 81: w = 2.000, loss=0.00000000
epoch 91: w = 2.000, loss=0.00000000
Prediction after training: f(5) = 10.000
