<a href="https://colab.research.google.com/github/byiringiroscar/NLP_FELLOWSHIP/blob/main/pytorch_documentation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import torch
import numpy as np

#create 1d torch

In [40]:
x = torch.empty(1) 

#create 2d torch

In [42]:
x = torch.empty(2, 3)
x

tensor([[2.9689e-34, 0.0000e+00, 0.0000e+00],
        [1.8750e+00, 0.0000e+00, 1.8750e+00]])

#create 3d torch 

In [45]:
x = torch.empty(3, 3, 3)
x

tensor([8.3268e-35, 0.0000e+00, 2.3694e-38])

#create empty zeros and ones

In [47]:
x = torch.zeros(2, 2) # 2d dimension
x

tensor([[0., 0.],
        [0., 0.]])

In [48]:
x = torch.zeros(2, 2, dtype=torch.int) # change dataype
x

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

#create your tensor 

In [51]:
x = torch.tensor([2.5, 0.1, 2.3]) # create 1d tensor
x

tensor([2.5000, 0.1000, 2.3000])

# let's see randon with torch , add, sub, div , mul

In [52]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x

tensor([[0.7788, 0.8178],
        [0.7352, 0.0403]])

In [ ]:
z = x + y
z = torch.add(x, y)

inplace addition


In [53]:
y.add_(x) # inplace will modifie y variable add with x
y

tensor([[1.7394, 1.7856],
        [1.1796, 0.1918]])

In [ ]:
z = torch.sub(x, y)
z = x-y
z = torch.mul(x, y)
z = x*y
z = torch.div(x, y)
z=x/y

#create random with 2d dimension then do slicing

In [58]:
# remember rows go vertical | and column go horizontal __  and(rows, column)
x = torch.rand(5, 3)
print(x)
print(x[:, 1]) # this will print all rows in column 1
print(x[1,:]) # this will print rows 1 and all column  

tensor([[0.8003, 0.2284, 0.1760],
        [0.3481, 0.2541, 0.1725],
        [0.8359, 0.2989, 0.4382],
        [0.0129, 0.8112, 0.0985],
        [0.8224, 0.7804, 0.4132]])
tensor([0.2284, 0.2541, 0.2989, 0.8112, 0.7804])
tensor([0.3481, 0.2541, 0.1725])


In [61]:
print(x[1,1])
print(x[1,1].item()) # print actual element 

tensor(0.2541)
0.254083514213562


#reshape tensor

In [63]:
x = torch.rand(4,4)
y = x.view(16) #  4*4 = 16
print(y) # will be in 1d

tensor([0.4708, 0.4628, 0.4289, 0.9754, 0.9994, 0.5505, 0.4278, 0.9982, 0.4094,
        0.3499, 0.8449, 0.9647, 0.7932, 0.1635, 0.7031, 0.4025])


In [65]:
y = x.view(-1, 8) # this will take 2d with 8,8

#convert tensor to numpy

In [67]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [68]:
b = a.numpy()
print(type(b)) # convert a tensor to numpy array

<class 'numpy.ndarray'>


N:B when we tensor are running on cpu not on gpu will share same memory then effect from one it will effect others
because they are sharing same memory location

In [74]:

a
a.add_(1)

tensor([4., 4., 4., 4., 4.])

In [75]:
b

array([4., 4., 4., 4., 4.], dtype=float32)

In [76]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [77]:
b = torch.from_numpy(a) # by default it will have datatype torch.float64

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [78]:
a += 1

In [79]:
a

array([2., 2., 2., 2., 2.])

In [80]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

#if we are running on cuda toolkit

In [82]:
# we can check it by this
if torch.cuda.is_available():
  device = torch.device("cuda") # when you are on window and you have cuda available
  #create tensor on gpu
  x = torch.ones(5, device=device) # this will create tensor then put on gpu
  # or we can do like this
  y = torch.ones(5)
  y = y.to(device=device) # and it will be much fast
  z = x +y
  #z.numpy() # this will return error because numpy handle cpu tensor we have to move it back to cpu
  z = z.to("cpu")
else:
  print("no")

no


In [85]:
x = torch.ones(5, requires_grad=True) # this will pytorch that we will be using gradient in optimization later
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

#autograd